# -*- coding: utf-8 -*-
"""Análise Exploratória de Dados 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IbNSY-GOXWCk5mqxMejqPYz2hiMym_x8
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Criando a tabela
dados = pd.DataFrame({
    "Nome": ["Ana", "João", "Maria", "Lucas", "Carla", "Paulo", "Bruna", "Marcos", "Júlia", "Fernanda"],
    "Idade": [25, 32, 28, 40, 29, 35, 27, 22, 30, 33],
    "Cidade": ["Salvador", "Salvador", "Feira", "Ilhéus", "Feira", "Salvador", "Itabuna", "Feira", "Ilhéus", "Salvador"],
    "Valor_gasto": [350, 420, 150, 1000, 200, 500, 250, 120, 800, 400]
})

print(dados.head())
print(dados.info())
print(dados.describe())
print(dados["Cidade"].value_counts())

sns.countplot(x="Cidade", data=dados)
plt.show()

sns.countplot(x="Cidade", data=dados, hue="Idade")
plt.show()

sns.barplot(x="Cidade", y="Valor_gasto", data=dados)
plt.show()

sns.boxplot(x="Cidade", y="Valor_gasto", data=dados)
plt.show()